services:
  - type: web
    name: foxbase-backend
    env: docker
    plan: starter
    region: singapore
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
      # Dưới đây bạn nên chỉnh lại theo DB của bạn
      - key: DB_URL
        value: jdbc:mysql://your-db-host:3306/foxbase
      - key: DB_USERNAME
        value: your_user
      - key: DB_PASSWORD
        value: your_password
